import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Provider from "@/component/Provider";
import ResponsiveAppBar from "@/component/Navbar/Navbar";
import UserContextProvider from "@/context/UserContextProvider";

import { Container } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <UserContextProvider>
            <Provider>
              <ResponsiveAppBar />
        <Container className="">
              {children}
        </Container>
            </Provider>
          </UserContextProvider>
          <ToastContainer />
      </body>
    </html>
  );
}
